### ISSUE TITLE
Offline

### ISSUE THREAD

**Issue by tkit0428** [Offline-CheatBreaker/Client#34] opened 2022-08-13 19:07 UTC
### Environment

Launcher

### Describe the suggestion

It'll be a perfect client/launcher if you can play it offline. I don't know how the codes work but is it able to play it offline? That will be a replacement for vanilla. Tsym devs the client/launcher is awesome in 2022

**Comment by ShonP40** [comment] 2022-08-13 19:10
Duplicate of #33

**Closed by ShonP40** 2022-08-13 19:10 UTC
Labels: enhancement

**Comment by tkit0428** [comment] 2022-08-13 19:13
No I'm saying will devs add this feature?

**Comment by ShonP40** [comment] 2022-08-13 19:17
It's not planned and we don't have a good way of implementing that at the moment.

If you want to play without an internet connection, simply launch the game while being connected to the internet, close the launcher and disconnect your internet connection.
