### ISSUE TITLE
Launcher is stuck at downloading

### ISSUE THREAD

**Issue by johnnyhyper123** [Offline-Cheatbreaker/Client#8] opened 2021-02-22 08:12 UTC
**Describe the bug**
When i try to play 1.8.9 ( i dont use 1.7) it launches the first time but them the next time i try to launch it, it gets stuck at downloading and i have to restart my pc to launch the game one time only.
**To Reproduce**
1. Go to cheatbreaker client
2. Click on play 1.8.9
3. Scroll down to anywhere

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g. `macOS 11.1`]
 - Game version [e.g. `1.7.10`]
 - Game build number [e.g. `2d8a7ac`]
 - Launcher version [e.g. `2.0.0 Beta 6`]
 - If on **Linux**, provide the output of `java -version` from Terminal
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

**Additional context**

**Comment by ShonP40** [comment] 2021-02-22 08:26
Edit your message and fill out these details so I could help

![image](https://user-images.githubusercontent.com/13995143/108681982-6d560f00-74f8-11eb-9004-ef3b88012268.png)

**Comment by ShonP40** [comment] 2021-02-22 08:35
But to me, it sounds like you're using an older version of our launcher (Beta 6 in particular).

You can download the latest one through our website: https://offlinecheatbreaker.com

**Comment by johnnyhyper123** [comment] 2021-02-22 09:00
I just checked and im using beta 8 which is the latest version right now.

**Comment by ShonP40** [comment] 2021-02-22 11:16
> Edit your message and fill out these details so I could help
> 
> ![image](https://user-images.githubusercontent.com/13995143/108681982-6d560f00-74f8-11eb-9004-ef3b88012268.png)

Still waiting for you to fill this out…

**Comment by ILOVECHEATING** [comment] 2021-02-22 13:17
Try to launch 1.7.10 first before then launch 1.8 😺

**Comment by ShonP40** [comment] 2021-02-22 13:20
This issue was fixed with Beta 7 already.
He wouldn't have it unless he's using Beta 6.

**Comment by johnnyhyper123** [comment] 2021-02-22 17:22
alright i updated it to show my java version, also if you look at the bottom it says beta 8
![image](https://user-images.githubusercontent.com/67174060/108744921-5c54d000-74ef-11eb-9d3c-d0d4096b1997.png)

**Comment by johnnyhyper123** [comment] 2021-02-22 17:26
My first launch is fast but after I restart the launcher, it will be stuck at downloading and ive waited for about a hour before and it still did not launch.

**Comment by ShonP40** [comment] 2021-02-22 17:28
On Beta 8 or older?

**Comment by johnnyhyper123** [comment] 2021-02-22 17:29
Beta 8.

**Comment by ShonP40** [comment] 2021-02-22 17:29
Also, are you running Ubuntu? Or a different Linux distribution?

**Comment by johnnyhyper123** [comment] 2021-02-22 17:30
Im using debian, but the .deb file wouldnt work so i used the appimage.

**Comment by ShonP40** [comment] 2021-02-22 17:31
Oh, so you need to install normal Oracle JDK
OpenJDK won't work with CB

**Comment by johnnyhyper123** [comment] 2021-02-22 17:32
Alright thanks ill go try and see if it works

**Comment by orilly** [comment] 2021-02-22 19:09
I have this issue too; I have Oracle JDK and am running the most recent Cheatbreaker version (installed 6 hours ago) on Windows 10 64-bit. It's been stuck on downloading for a good 2 hours now.

**Comment by CokiCola** [comment] 2021-02-22 22:22
Yea, Having the same issue on beta 8

**Comment by ShonP40** [comment] 2021-02-22 22:39
Anyone on Windows that’s experiencing issues with the launcher stuck on Downloading, should check their firewall to make sure that it doesn’t block the launcher.

**Comment by johnnyhyper123** [comment] 2021-02-23 00:14
Just launched cheatbreaker again after having it crash, its stuck at downloading again.

**Comment by ShonP40** [comment] 2021-02-23 09:01
Can you run `java -version` again and make sure that it says Oracle JDK and not OpenJDK?

**Comment by johnnyhyper123** [comment] 2021-02-23 17:51
it doesnt say oracle java but it did change 
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Comment by ShonP40** [comment] 2021-02-23 18:20
Can you go to `~/.config/'Offline CheatBreaker'` and send the `log.log` file to our email (support@offlinecheatbreaker.com)?
You can send it here as well, just make sure to remove any personal stuff you might have in that file (e.g. chat logs, Linux username) as its a full game & launcher log.

**Comment by johnnyhyper123** [comment] 2021-02-23 21:05
alright

**Comment by johnnyhyper123** [comment] 2021-02-23 21:14
Ok, I sent them.

**Comment by ShonP40** [comment] 2021-02-23 21:17
Can you send it as a file?

**Comment by johnnyhyper123** [comment] 2021-02-24 00:47
sure

**Comment by johnnyhyper123** [comment] 2021-02-24 00:50
just replied to the email i sent with the file

**Comment by ShonP40** [comment] 2021-02-24 08:17
I don’t see any errors in your log that could be related to the issue you are experiencing.

1. Which Debian version are you using?
2. Can you close the launcher and the game, open the launcher again, let it load completely and then try to launch again (give it a couple minutes).
3. After that, send us the `log.log` file again.

**Comment by johnnyhyper123** [comment] 2021-02-24 17:47
Im using debian stretch.

**Comment by ShonP40** [comment] 2021-02-24 18:53
Well, we never tested the launcher on such an old version.
Debian Buster is the latest.

Can you close the launcher and the game, open the launcher again, let it load completely and then try to launch again (give it a couple minutes).
After that, send us the `log.log` file again.

**Comment by johnnyhyper123** [comment] 2021-02-26 22:35
sorry for not responding in so long, but heres the log file
[log.log](https://github.com/Offline-Cheatbreaker/Client/files/6052831/log.log)

**Comment by ShonP40** [comment] 2021-02-26 22:57
There are no errors in your log.

Can you try to install the deb version again by using this command (in the directory you downloaded the deb file to): `sudo dpkg -i Offline_CheatBreaker_Beta.deb`?

**Comment by johnnyhyper123** [comment] 2021-03-04 08:34
it installs, but when i try to launch it nothing happens.

**Comment by ShonP40** [comment] 2021-03-04 08:36
When you try to open the launcher, or launch the game?

**Comment by johnnyhyper123** [comment] 2021-03-04 08:37
open the launcher

**Comment by ShonP40** [comment] 2021-03-04 08:38
hmm
Can you try to restart your PC?

**Comment by johnnyhyper123** [comment] 2021-03-04 08:54
ive already done that before

**Comment by ShonP40** [comment] 2021-03-04 08:57
Alr, so, I made a Debian Stretch VM and encountered the same issue.

However, I found a solution:
1. Open Terminal
2. `cd /usr/bin/.offlinecheatbreaker`
3. `sudo chown root:root chrome-sandbox`
4. `sudo chmod 4755 chrome-sandbox`

After that, you should be able to open the launcher using the shortcut in the apps menu.

**Comment by johnnyhyper123** [comment] 2021-03-04 12:50
still wont load

**Comment by ShonP40** [comment] 2021-03-04 16:12
Can you try to run the following command from terminal and send me its output if the launcher doesn't open?

`"/usr/bin/.offlinecheatbreaker/Offline CheatBreaker"`

**Comment by johnnyhyper123** [comment] 2021-03-04 17:03
-bash: /usr/bin/.offlinecheatbreaker/Offline: No such file or directory

**Comment by ShonP40** [comment] 2021-03-04 17:06
You need to type it with the quotes...

**Comment by johnnyhyper123** [comment] 2021-03-04 17:29
the launcher opens now but it still has the downloading problem and it only says: "(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397" which it always did on the appimage

**Comment by johnnyhyper123** [comment] 2021-03-04 17:29
the launcher opens now but it still has the downloading problem and it only says: "(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397" which it always did on the appimage

**Comment by ShonP40** [comment] 2021-03-04 17:47
1. When it starts downloading for the first time since you installed the `.deb` version of this launcher, give it some time. First launch always takes longer
2. After checking again, I can confirm that it gets stuck on `Downloading` when you try to launch it the second time without waiting about 2-5 min between launches. This seems to be a Debian Stretch only issue though, Never happened on Ubuntu. I'll check it on Debian Buster as well

**Comment by ShonP40** [comment] 2021-03-04 18:29
Yea, its a Debian Stretch only issue.
Works completely fine on Buster.

**Comment by ShonP40** [comment] 2021-03-04 19:40
Posted an [OS compatibility list](https://github.com/Offline-Cheatbreaker/Client/blob/master/OS%20compatibility.md)

**Comment by johnnyhyper123** [comment] 2021-03-10 22:01
Alright, thanks.

**Closed** 2021-03-14 14:16 UTC
Labels: bug
